### ISSUE TITLE
sort error on TPTP file

### ISSUE THREAD

**Issue by apease** [vprover/vampire#101]
I've done a git pull and make vampire_rel to get the latest as of Dec 2.  I have a test file I've pared down to just one axiom

fof(kb_SUMO_3,axiom,(( ( ! [V__ARG,V__N,V__VAL,V__ARGS2] : (  s__instance(V__VAL,s__Quantity)) => ((s__ListFn__1Fn(V__ARGS2) & (V__VAL = s__ListOrderFn(s__ListFn__1Fn(V__ARGS2),V__ARG))) => s__greaterThan(V__VAL,V__N))) ) ))).

the file extension is .tptp

I run Vampire and get

$ /home/apease/workspace/vampire/vampire --mode casc -t 30 /home/apease/.sigmakee/KBs/temp-comb-small.tptp
% Exception at proof search level
Parsing Error on line 1
The sort $o of function argument s__ListFn__1Fn(X3) does not match the expected sort $i

Since no sorts are given in the axiom, since it's TPTP, and no built in types or functions are used, why does Vampire think the argument should be an integer? Very sorry if I'm missing something obvious.

**Comment by quicquid** [comment]
Hello! Your axiom contains `s__ListFn__1Fn` twice, once as a predicate after the conjunction and once as a function within `s__ListFn__1Fn`. The return type of a predicate is boolean(`$o`) whereas the return type of the function is an individual term (`$i`) and vampire reports that it can't be both. Can you double-check if the axiom says what you want?

**Comment by apease** [comment]
thank you and sorry I didn't catch this myself

**Comment by quicquid** [comment]
By the way: the forall operator `!` binds stronger than the binary logical operators i.e. you probably want to put parenthesis around the formula (you can see the difference when you try to prove  `fof(c1, conjecture, ![X] : (p(X) | ~p(X))).` vs `fof(c1, conjecture, ![X] : p(X) | ~p(X)).`). On the other hand, many of the parenthesis you used are not necessary. Your input formula is equivalent to:

` ! [ARG,N,VAL,ARGS2] : instance(VAL,quantity) => ((listFn(ARGS2) & (VAL = listOrder(listFnx(ARGS2),ARG))) => greaterThan(VAL,N))`

**Comment by apease** [comment]
I used to add parens after quantifiers, but Giles reported there's a problem with that (that I had encountered).  I've put an example from our correspondence below.  Has that been fixed recently?

------------------------------------------
The short answer is that if you write

tff(kb_SUMO_3175b,axiom,(! [V__Y : $real] : 
  (s__MeasureFn__1ReFn(V__Y, s__TonMass)) = 
   (s__MeasureFn__1ReFn($product(V__Y, 2000.0), s__PoundMass)))).

as this

tff(kb_SUMO_3175b,axiom,(! [V__Y : $real] : 
   s__MeasureFn__1ReFn(V__Y, s__TonMass) = 
   s__MeasureFn__1ReFn($product(V__Y, 2000.0), s__PoundMass))).

then Vampire should parse it correctly.

**Comment by quicquid** [comment]
You have two kinds of superfluous parenthesis in your file: the ones around terms like `(f(X)) = 1` and the additional parenthesis around the forall like `(![X] : p(X) | ~p(X))`. I assume it is the first kind that confuses the vampire parser. Please be aware that it is the formula after the colon that needs to be within parenthesis for the grouping to work correctly:  `(![X] : p(X) | ~p(X))` is still the same as  `(![X] : p(X) | ~p(Z))` wheras `![X] : (p(X) | ~p(X))` has both occurrences of X bound to the quantifier.

**Comment by apease** [comment]
I'm afraid I'm not understanding.  In my correspondence with Giles shown above, it is a set of parentheses enclosing a formula after the colon that appears to cause a problem.

**Comment by apease** [comment]
I understand the quantifier scope issue, and that's an unintended consequence of solving the problem parsing the quantified equality.  Do I only remove parens for quantified equalities?  Or has someone solve the problem parsing quantified equalities such that I can go back to putting parens around quantified formulas without triggering a parsing problem?

**Comment by quicquid** [comment]
The quantifier from your conversation with Giles has only one atom as argument (the equality predicate), so there is no parenthesis necessary. `! [Y : $real] : measure(Y, ton) = measure($product(Y, 2000.0), pound)` should parse fine although it is no error to put the parenthesis around the whole equation: ! [Y : $real] : ( measure(Y, ton) = measure($product(Y, 2000.0), pound) ). What you tried is to put each argument of the equality into parenthesis and i believe this messes up the parser ( i.e. `(a) = (b)` fails but `(a = b)` works).

**Comment by apease** [comment]
Many thanks for clarifying.  It looks like I misunderstood Giles' fix

**Comment by quicquid** [comment]
It's a little tricky because all other infix operators are boolean, so for conjunction / disjunction / implication / logical equivalence to be grouped together, you will need to parenthesis around the formulas (like in the examples before). It's the equality that's the exception. Please also note that term equality is written as `=` whereas logical equality is written as `<=>` - the latter is often denoted by `=`  in texts about predicate logic without equality, which can be confusing some times.
