### ISSUE TITLE
vampire_z3 SMT mode fails to find sat on a simple example

### ISSUE THREAD

**Issue by dde-cls** [vprover/vampire#111]
Consider the following SMT-LIB input:

> 
> (set-logic AUFNIRA)
> (set-option :print-success false)
> (declare-fun g_tt_0 () Int)
> (define-fun |def_inv_0| () Bool (and (>= g_tt_0 0) (<= g_tt_0 10)))
> (assert (! |def_inv_0| :named |inv0|))
> (assert (! (= g_tt_0 8) :named goal))
> (check-sat)
> (exit)

vampire_z3 fails to find quickly that it is satisfiable, while z3 by itself does almost instantaneously. In this case, it has been called by the following script:

> 
> #!/bin/bash
> ulimit -t 3
> LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH $HOME/bin/vampire_z3-4.4.0 --mode smtcomp $1
>

**Comment by selig** [comment]
Vampire will never return 'satisfiable' for a problem containing theories as it never tries to be complete. For theory problems, Vampire only tries to find unsatisfiability and gives up if it cannot. There was a special case where Vampire would pass a ground problem directly to z3 (and return its answer) but this was turned off at some point.

**Comment by dde-cls** [comment]
Thank you for your answer. I will close this ticket as it relates to a feature that is not in the scope of Vampire.
