### ISSUE TITLE
Compile error in Shell/TrivialPredicateRemover.cpp

### ISSUE THREAD

**Issue by JakobR** [vprover/vampire#113]
I'm getting the following compile error with the latest master branch (commit d51e4de6137717c7c39b87709a28cb681892a96c). It seems that `Clause::isGoal()` was removed at some point but it is still being used in `TrivialPredicateRemover`.

```
../Shell/TrivialPredicateRemover.cpp:71:14: error: no member named 'isGoal' in 'Kernel::Clause'
       !(cl->isGoal() && env.options->ignoreConjectureInPreprocessing())) {
         ~~  ^
1 error generated.
```

**Comment by selig** [comment]
Ah okay, I just ran Make and not CMake... TrivialPredicateRemover is not currently used so isn't compiled by Make but it seems that CMake is trying to compile it anyway.

cl->isGoal() has been renamed to cl->inference()->derivedFromGoal()

I've fixed this line and checked that CMake builds as well

**Comment by JakobR** [comment]
Thank you!
