### ISSUE TITLE
How can one disable the SZS proof output in casc mode?

### ISSUE THREAD

**Issue by AbdallahS** [vprover/vampire#117]
When I run vampire (tested with 4.4 or 4.0) with the command

    vampire --statistics none --time_statistics on --time_limit 300s --mode casc --proof off trivial_dumb.tptp

The output contains

    % SZS status Theorem for trivial_dumb
    % SZS output start Proof for trivial_dumb
    fof(f507,plain,(
      $false),
      inference(avatar_sat_refutation,[],[f177,f184,f187,f237,f506])).
    ...
    fof(f111,plain,(
      ~direct | sP0),
      inference(cnf_transformation,[],[f84])).
    % SZS output end Proof for trivial_dumb

When I run the same command but with `--proof on`, I get the same output that includes a proof in tptp format (lines starting with `fof`).

On the other hand, if I change `--mode vampire` then `--proof off` doesn't display the proof, as intended.

    vampire --statistics none --time_statistics on --time_limit 300s --mode vampire --proof off trivial_dumb.tptp

And `--proof on` displays a proof in a different format than tptp, e.g.,

    369. $false <- (10, 12, 14, 20) [subsumption resolution 368,366]
    370. ~10 | ~12 | ~14 | ~20 [avatar contradiction clause 369]
    371. $false [avatar sat refutation 177,184,191,192,193,194,198,205,212,216,223,230,234,246,350,370]

So it seems to me that `--mode casc` just ignores the option `--proof`. Is that intended? If so, is there another option for me to not display the proof when I use mode casc?

**Comment by selig** [comment]
Hi,

`--mode casc' is shorthand for `--mode portfolio --schedule casc --proof tptp --output_axiom_names on --output_mode szs`

So you could just run `--mode portfolio --schedule casc --output_axiom_names on --output_mode szs` to get what you want

Alternatively, you can 'force' the option you want on top of casc mode by adding `--forced_options p=off'. To get details on how this option works run `vampire -explain forced_options`.

**Comment by AbdallahS** [comment]
Ah yes, I understand. The `--forced_options proof=off` approach solves my problem. Thank you!
