### ISSUE TITLE
Downloading vampire-4.3.0

### ISSUE THREAD

**Issue by izumi-h** [vprover/vampire#122]
Hi, I downloaded the vampire-4.3.0 from [here](https://github.com/vprover/vampire/releases/tag/4.3.0).
When I did `make vampire` in the directory, ERROR happened in Lib/Recycler.hpp.
For this reason, I copied the same file from vampire-4.4 and ran it again, and it worked.
However, the version of that vampire was 4.2.2, not 4.3.0.
What should I do to use vampire-4.3.0?

**Comment by quickbeam123** [comment]
Hi, could you please provide more details? 

What error did you get from `Lib/Recycler.hpp`? What compiler/version were you using?

We might have a mistake in the version numbering. Perhaps the 4.3.0 tag internally "thinks" it's 4.2.2. How did you check the version of the obtained executable? (Was it `./vampire --version`?)

Finally, vampire-4.3.0 will be 2 years old soon. Are you sure you want to be using it? If so, would a statically linked executable satisfy your needs?

**Comment by izumi-h** [comment]
Thank you for the reply.

I got the following error when running `make vampire`:
```
In file included from ./Lib/Metaiterators.hpp:35:
./Lib/Recycler.hpp:87:29: fatal error: 'isNonEmpty' following the 'template' keyword does
      not refer to a template
      while (this->template isNonEmpty())
                            ^
```
I use the C++ version of `10.0.1`.
In vampire-4.4, the code is replaced by `while (this->isNonEmpty())`.

> How did you check the version of the obtained executable? (Was it ./vampire --version?)

Yes, I check the version by: 
```
./vampire --version
Vampire 4.2.2 (commit unknown)
```

> Are you sure you want to be using it? If so, would a statically linked executable satisfy your needs?

Yes. In my project (https://github.com/izumi-h/ccgcomp), I used version 4.3.0 (which works best). A statically linked executable would be very helpful to reproduce the results.

**Comment by quickbeam123** [comment]
I can confirm that the version string was by mistake not updated for 4.3.0 and so --version saying 4.2.2 is fine.

Please try out https://github.com/vprover/vampire/releases/download/CASC_2018/Vampire---4.3.zip

for the statically linked executable of that version of vampire.

**Comment by izumi-h** [comment]
Thanks!
