### ISSUE TITLE
Condition in file FMB/SortInference.cpp, line 734 violated

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#136]
./vampire_dbg_master_4779 --input_syntax smtlib2  --decode fmb+10_1_av=off:fmbes=contour:fmbsr=1.5:ile=on:updr=off_28 UF/sledgehammer/TwoSquares/uf.794486.smt2
Condition in file FMB/SortInference.cpp, line 734 violated:
createNew
----- stack dump -----
Version : Vampire 4.5.1 (commit 77e82df6 on 2020-07-31 17:57:13 +0200)
Control points passed: 21525231
last control point:
         -DHMap::find/2 (21525231)
main
 vampireMode()
  doProving()
   ProvingHelper::runVampireSaturation
    ProvingHelper::runVampireSaturationImpl
     MainLoop::run
      FiniteModelBuilder::init
       SortInference::doInference
        SortInference::getDistinctSort
----- end of stack dump -----

**Comment by selig** [comment]
Can no longer reproduce in master. This may have been impacted by the refactoring of sorts with the introduction of polymorphism. It  may also resurface when we do some testing of the new PR but I am closing for now.
