### ISSUE TITLE
Condition n < _size in file ./Lib/DArray.hpp, line 121 was violated (perhaps related to #136)

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#137]
./vampire_dbg_master_4779 --input_syntax smtlib2  --decode fmb+10_1_av=off:fmbes=contour:fmbsr=1.5:ile=on:updr=off_28 UF/sledgehammer/Fundamental_Theorem_Algebra/uf.717973.smt2
Condition n < _size in file ./Lib/DArray.hpp, line 121 was violated, as:
n == 0
_size == 0
----- stack dump -----
Version : Vampire 4.5.1 (commit 95d66246 on 2020-08-04 09:51:33 +0100)
Control points passed: 957353
last control point:
               +DArray::operator[] const (957353)
main
 PortfolioMode::perform
  PortfolioMode::searchForProof
   PortfolioMode::performStrategy
    PortfolioMode::runSchedule
     ScheduleExecutor::run
      ScheduleExecutor::spawn
       PortfolioSliceExecutor::runSlice
        PortfolioMode::runSlice
         PortfolioMode::runSlice(Option&)
          ProvingHelper::runVampire
           ProvingHelper::runVampireSaturationImpl
            MainLoop::run
             FiniteModelBuilder::init
              DArray::operator[] const
----- end of stack dump -----

**Comment by selig** [comment]
Can no longer reproduce in master. Almost certainly related to sorts. May resurface with testing but closing for now.
