### ISSUE TITLE
In Multicore (num slave processes > 1) portfolio mode a proof being printed may be interrupted a failure comment from another process

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#146]
We already make sure that only one proof gets ever printed. So this is really just the failure comment lines. It seems an overkill  to acquire a semaphore for synchronising on these. 

Maybe, if the user really cares about proofs, we should support printing them to a specified file rather than on stdout?

**Comment by ibnyusuf** [comment]
With the recent changes to printing, I think this issue can now be closed?

**Comment by quickbeam123** [comment]
Good point, @ibnyusuf !
