### ISSUE TITLE
Proposal: Automatic detection of input syntax

### ISSUE THREAD

**Issue by gleiss** [vprover/vampire#198]
## Motivation
Vampire supports input written in the TPTP- and the SMT-LIB2-syntax. Currently, Vampire interprets its input by default using TPTP, which can be changed to SMT-LIB2 with the option `--input_syntax smtlib2`.

While the current behaviour is nice if you prefer TPTP, it is not optimal for users prefering SMT-LIB2, due to the following reasons:
- it is cumbersome for a user to type `--input_syntax smtlib2` all the time.
- the user needs to know that it's possible to change the input syntax to SMT-LIB2 and that it is possible to do so using `--input_syntax smtlib2`. Note that this might in particular be a problem for new (industrial) users of Vampire.

If you are using TPTP, you might ask why others don't do the same. There are several reasons for that:
- SMT-LIB2 is the de facto standard in industrial applications of theorem provers, so industrial users might already be familiar with SMT-LIB2, but not with TPTP.
- Some features of Vampire are only accessible using SMT-LIB2 syntax, for instance native term algebras or recursive function definitions, so if you need these features, you have to use SMT-LIB.
- (arguable reasons for why SMT-LIB2 is a better input format than TPTP in some context ;) )

## Proposal
Here is a proposal to improve the current situation using an automatic detection of the input syntax (including some tips from @quickbeam123):
- change the values for `--input_syntax` to `auto`, `tptp`, and `smtlib2`, with default value `auto`
- with the `auto` option value, Vampire uses the file extension of the input file to decide which input syntax is used. If the ending is one of `smt`, `smt2`, `smtlib`, `smtlib2`, then Vampire uses SMT-LIB2 syntax, otherwise it uses TPTP syntax.
- with the option value `tptp` resp. `smtlib2`, Vampire uses TPTP resp. SMT-LIB2 syntax (independently from the file extension)

Additionally, for the `auto` option value, Vampire could output a message, which informs the user about the detected language, e.g. `Assuming SMT-LIB2 input syntax, since file extension is "smt2"`, or `Assuming TPTP input syntax, since file extension is not one of "smt", "smt2, "smtlib", "smtlib2"`. We should only print such a message in the modes which are allowed to be chatty.

Some thoughts on the proposed solution:
- The solution tries to cover the most relevant cases for SMT-LIB2 users, but at the same time tries to preserve the current behaviour as much as possible.
- By default, this solution should detect the right input format for almost all users. In particular it works for SMT-LIB2 users, which use `smt`, `smt2`, `smtlib`, `smtlib2` as file extension, and it works for TPTP users, who use `tptp`, `p`, or `in` as file extensions.
- A suspicious user, who does not trust the automatic detection, can always set the input syntax explicitly to get the assurance that the chosen syntax is used by Vampire
- The modes used for CASC and SMTCOMP are not affected, as these modes set the input syntax explicitly.
- The detection takes a constant amount of time and is super-fast for files of arbitrary size.
- Vampire will produce a parsing error, if a user provides a file, which contains TPTP syntax but uses one of the file extensions `smt`, `smt2`, `smtlib`, `smtlib2`, and at the same time does not specify `--input_syntax tptp`. This behaviour of Vampire seems to be acceptable.
- Vampire will produce a parsing error, if a user provides a file, which contains SMTLIB2 syntax but uses e.g. a file extension `in` or `p`, and at the same time does not specify `--input_syntax smtlib2`. This behaviour of Vampire seems to be acceptable too.
- As an alternative to inspecting the file extension, one could also start parsing the file and use the first matched structure to detect the input syntax. This solution could improve on the currently proposed solution, but it is not clear to me whether its advantages outweigh the potential downsides (speed for huge input files, maintainability in the case of changes to the languages).

Let me know what you think, cheers!

**Comment by MichaelRawson** [comment]
Great proposal! I think auto-by-file-extension approach is reasonable. Almost all the time there is an input file, and if you're e.g. piping into Vampire, it's not that surprising that you need to set the input syntax explicitly.

Some points:
* Agree that detection by trying to parse it sounds like a nightmare, let's try not to do that.
* Is `.ax` also a reasonable filename for TPTP-detection? I can see you might reasonably want to check validity of an axiom set.
* If we have C++17 there's https://en.cppreference.com/w/cpp/filesystem/path/extension - just saying. ;-)

**Comment by selig** [comment]
I think it's a good proposal. The reason I didn't attempt to add an auto mode before was that I didn't want to bother with trying to detect the language via parsing. Basing it on file extension does seem to cover the main cases.

The non-chatty output modes are currently --output_mode smtcomp/spider... but perhaps we should separate out verbosity of output from the 'status' returned (another issue).

**Comment by gleiss** [comment]
Great! I will try to find some time this week to come up with an implementation.

@MichaelRawson: Yes, any file extension for TPTP-syntax - including `ax` - would be supported, as long as it's not one of the 4 SMT-LIB2 extensions `smt`, `smt2`, `smtlib`, `smtlib2`. In my experience, the TPTP users vary their file extensions much more than the SMT-LIB2 users (`smt2` seems to be the most used extension), which is why I thought it would make sense to detect the file extensions indicating SMT-LIB2 and consider everything else to be a file extension indicating TPTP.

**Comment by easychair** [comment]
If this is done, this should be done properly, by looking at the file
content, not its extension.

A

**Comment by gleiss** [comment]
Ok, so let me quickly wrap up for future reference:
- I motivated the urge for improving on the current situation
- I carefully argued why the proposed solution improves the current situation a lot, and why it should work in more than 99,9% of the cases.
- @MichaelRawson, @selig and I agreed that detecting the input syntax by looking at the file content is nothing we want to do, as it is hard to get it right, with unclear downsides regarding speed and more importantly regarding maintainability.
- Andrei decided that we either (i) anyway implement a solution which looks at the file content to get the additional 0,1% (with unclear downsides regarding speed and maintainability), or we (ii) don't do anything and stick with the current problematic situation.
- So nothing will happen and a convenient usage of Vampire will remain a privilege of the TPTP ivory tower.

This is really frustrating, I'm closing this issue.

**Comment by laurakovacs** [comment]
I think we should re-open the discussion and Bernhard's proposal on automatic detection of input syntax.  So I re-open it. 

Andrei did not decided, but made a suggestion that can be used for further improvements. 

Starting however with detecting possible input format using file extensions is more than just a good start, I would also support it.

**Comment by selig** [comment]
For interest, I just checked and CVC4 sets lang based on file extension by default, similar to the proposal here. In fact they do this

` if(opts.getInputLanguage() == language::input::LANG_AUTO) {
    if( inputFromStdin ) {
      // We can't do any fancy detection on stdin
      opts.setInputLanguage(language::input::LANG_CVC4);
    } else {
      unsigned len = filenameStr.size();
      if(len >= 5 && !strcmp(".smt2", filename + len - 5)) {
        opts.setInputLanguage(language::input::LANG_SMTLIB_V2_6);
      } else if((len >= 2 && !strcmp(".p", filename + len - 2))
                || (len >= 5 && !strcmp(".tptp", filename + len - 5))) {
        opts.setInputLanguage(language::input::LANG_TPTP);
      } else if(( len >= 4 && !strcmp(".cvc", filename + len - 4) )
                || ( len >= 5 && !strcmp(".cvc4", filename + len - 5) )) {
        opts.setInputLanguage(language::input::LANG_CVC4);
      } else if((len >= 3 && !strcmp(".sy", filename + len - 3))
                || (len >= 3 && !strcmp(".sl", filename + len - 3))) {
        // version 2 sygus is the default
        opts.setInputLanguage(language::input::LANG_SYGUS_V2);
      }
    }
  }
`
https://github.com/CVC4/CVC4/blob/master/src/main/driver_unified.cpp Line 112

I appreciate that something that detects the language based on the actual content would be better but if we're not going to get that then the next best thing is something that does something reasonable and unsurprising.

**Comment by easychair** [comment]
Two things:

(1) Somebody mentioned 0.1% overhead - you must be kidding - theorem
proving problems are not solved at the speed of reading 1-2K lines of text.
If you use a full parser until it chokes off and says "sorry, I cannot
understand it" you would hardly go beyond 1-2 lines.

(2) My comment was based on dealing with EasyChair for many years. It is
customer-oriented. This is the person you don't want to be p..d off after
he or she used your system. If this person's comments are "why this stupid
requitrement" you are doing the wrong thing. Been based on file extensions
(unless it is .pdf) is wrong - there are no standards.

(3) While it is interesting to check what CVC4 does, the reference to it is
misleading. If we used "other guys do this and so we can/should do this" as
our slogan you would have never heard of Vampire. With this slogan at the
end everybody does The Wrong Thing because others do it. Complete
strategies only and the Discount loop only are two common examples.

Andrei

**Comment by selig** [comment]
My point of referring to CVC4 is that it is widely (much more than Vampire) and the inference is that they're not p..ssing off their customers with this feature that much.

One thing we should be doing, orthogonally to this discussion, is suggesting that the user specify 'input_syntax' when they get a parse error. The biggest question I get from users is how to make it work on SMTLIB problems, even though it's pretty much all we say on the Usage page of the website. My hypothesis is that the current setup is probably confusing (perhaps not p..ssing off) users more than the proposed setup would.

Btw, I think the 0.1% was referring to the hypothetical number of cases where the file extension isn't p, tptp, smt2, etc rather than execution time. Whilst there aren't proper standards here there are de facto standards.

**Comment by laurakovacs** [comment]
I do not think we would p..ss off users by having lightweight cheap detection of input syntax, on the contrary. 
The file extension could help, should be cheap - and if it is not a correct TPTP/SMT syntax we just fall back to what we have now, give a warning of wrong input syntax.

**Comment by easychair** [comment]
I did not mean professional customers who would develop their own tools for
running.

I mean people like students or others who would like to try Vampire.

I also believe that if you do something, you should do it properly, in the
best possible way, unless it is extremely time consuming. You proposed
change will probably take the same time as a better analysis. The only
justification I see for your proposal is that "CVC4 does that".

A

**Comment by selig** [comment]
Note: a suggested method for addressing this issue was already merged (back in December). The code will run each parser on the input and fall back to the other parser (now we only have TPTP and SMT2) if it fails. It uses hints from the file name to choose which parser to try first.

Given this, I propose to close this Issue.
