### ISSUE TITLE
Please cut new release for new license

### ISSUE THREAD

**Issue by lukegb** [vprover/vampire#199]
Hi! I'm coming here from NixOS to ask if you wouldn't mind cutting a new release tag that includes your new license.

We'd like to mark vampire in NixOS as bsd3 rather than nonfree (https://github.com/NixOS/nixpkgs/pull/105528), but would feel more comfortable doing so if the LICENCE file in the repo at the tag we were shipping matched what our metadata contains, for easier spot-checking.

**Comment by MichaelRawson** [comment]
Thanks for packaging! I think this is solved with the 4.6 release now, right? @quickbeam123
