### ISSUE TITLE
Library for parsing the proofs

### ISSUE THREAD

**Issue by alebugariu** [vprover/vampire#220]
Is there any library one can use to parse the Vampire's proofs? We would like to extract some information from the proofs without having the input files for which the proofs were generated.

Thank you very much for your help.
Alexandra

**Comment by selig** [comment]
There are a couple of systems that parse TPTP proofs (set option -p tptp in Vampire to get such proofs). 

https://www.logic.at/gapt/
https://github.com/skbaek/tesc

and they might have some code you could borrow/adapt/use. Geoff Sutcliffe probably knows of others. The advantage is that many solvers output proofs in this format.

@MichaelRawson did you have an ad-hoc script for parsing native Vampire proofs at one point or did that use the TPTP format?

**Comment by MichaelRawson** [comment]
Circa 2017 I did something ad-hoc with the native output, it's fairly consistent and can usually be done with regular expressions or similar. Not sure I have it any more though. Perhaps you can expand a little on what you're doing with the Vampire proofs (we're always interested!) so we can point you in the right direction?

**Comment by alebugariu** [comment]
Thanks a lot, I think we will use regular expressions.
We are trying to "explain" the proofs to users who don't have experience with any particular proof format, to help them get a high level intuition of the source of the contradiction.

**Comment by selig** [comment]
This feels related to something Google Scholar told me about 

https://ethz.ch/content/dam/ethz/special-interest/infk/chair-program-method/pm/documents/Education/Theses/Pascal_Strebel_BA_Description.pdf

At one point I was working on making Vampire proofs more detailed, see 

https://easychair.org/publications/paper/1DlL

But I got distracted. The stuff I did got hidden behind the option "--proof_extra full". The step where I separate out instantiation steps was only applied to a few of the rules.

**Comment by alebugariu** [comment]
Indeed, my question is related to that project description (which is written by my student). 
Thank you for the paper, it's very helpful.

**Comment by MichaelRawson** [comment]
Looks like a solution was found. :-)
