### ISSUE TITLE
Question: Should the following work on Vampire?

### ISSUE THREAD

**Issue by Columpio** [vprover/vampire#221]
I have a (simple) CHC system over free sorts and functions, which is easily handled by CVC4. I thought it should also be easy for Vampire to handle, but it actually diverges.

The following code simply checks the evenness of the sum of the Peano integer with itself (`even (x + x)`). This property is obviously true, so CVC4 correctly halts with `sat`.
```smt
(set-logic ALL)
(declare-sort Nat 0)
(declare-fun Z () Nat)
(declare-fun S (Nat) Nat)
(declare-fun even (Bool Nat) Bool)
(assert (forall ((x Nat) (y Nat) (x1 Nat) (r Bool) (r1 Bool))
	(=>	(and (= r r1)
			(even r1 x1)
			(= x (S y))
			(= y (S x1)))
		(even r x))))
(assert (forall ((x Nat) (y Nat) (r Bool))
	(=>	(and (= r false)
			(= x (S y))
			(= y Z))
		(even r x))))
(assert (forall ((x Nat) (r Bool))
	(=>	(and (= r true)
			(= x Z))
		(even r x))))
(declare-fun add (Nat Nat Nat) Bool)
(assert (forall ((x Nat) (y Nat) (z Nat) (r Nat) (sum Nat))
	(=>	(and (= r (S sum))
			(add sum z y)
			(= x (S z)))
		(add r x y))))
(assert (forall ((x Nat) (y Nat) (r Nat))
	(=>	(and (= r y) (= x Z))
		(add r x y))))

; RUN CVC4 1.6 AS: 				cvc4 --finite-model-find FILENAME
; RUN VAMPIRE 4.5.1 (commit 57a6f78c) AS:	vampire --input_syntax smtlib2 FILENAME
(assert (forall ((x Nat) (twicex Nat) (iseven Bool))
	(=>	(and (= iseven false)
			(add twicex x x)
			(even iseven twicex))
		false)))
(check-sat)

```
I expect Vampire to somehow saturate the set and halt. Is this example to complex for Vampire to handle?

**Comment by quickbeam123** [comment]
Indeed, running vampire in a mode tailored for discovering satisfiable problems by, e.g., specifying `--mode casc_sat`, or more specifically invoking the finite model finder via `-sa fmb` cracks this...
