### ISSUE TITLE
Forbidden options don't work as expected in portfolio modes.

### ISSUE THREAD

**Issue by MichaelRawson** [vprover/vampire#231]
According to the help output, `--forbidden_option opt=val` should refuse to do anything if `opt` is set to `val`, implicitly or otherwise, _unless_ we're in a portfolio mode, in which case we will skip any such strategies. This is useful!

Most of the time this works as expected, but if the first strategy in a schedule is forbidden, we stop immediately, rather than skipping strategies. Compare:

```
$ vampire --mode portfolio --forbidden_options av=off Problems/GRP/GRP001-3.p
...
happily runs, skips strategies that switch AVATAR off
reports "user error" as it does, but whatever
```

and

```
$ vampire --mode portfolio --forbidden_options av=on Problems/GRP/GRP001-3.p
User error: option av uses forbidden value on
$ ?!
```

If this actually is a misfeature I'll dig around and fix it, otherwise let me know how I goofed!

**Comment by selig** [comment]
Just pushed a fix for this - we shouldn't check global constraints in CommandLine when in portfolio mode.

**Comment by selig** [comment]
I'm going to close but reopen if you think that this doesn't fix it...
