### ISSUE TITLE
Crashing when free variable is synonymous to a bound one inside the same formula

### ISSUE THREAD

**Issue by aztek** [vprover/vampire#24]
Normally, free variables are implicitly quantified at top level. However, when a free variable is synonymous to a bound one inside the same formula, Vampire crashes. An example to reproduce:

```
fof(1, axiom, (![X]: (X = i)) | (X = i)).
```

gives assertion violation in `TPTP::sortOf`.

**Comment by selig** [comment]
This was fixed a long time ago
