### ISSUE TITLE
Trivial saturation for a CHC system

### ISSUE THREAD

**Issue by Columpio** [vprover/vampire#240]
Hello, I am a newbie to saturation and Vampire in particular and I am trying to understand how this world works. I've heard that a set saturated by superposition represents a least (by inclusion; Hebrand) model of a Horn clause system [1].

I am trying to solve the following simple CHC system with Vampire:
```smt2
(set-logic ALL)
(declare-sort Nat 0)
(declare-fun zero () Nat)
(declare-fun succ (Nat) Nat)
(declare-fun leq (Bool Nat Nat) Bool)
(assert (forall ((x Nat) (y Nat) (b Bool))
	(=>	(leq b x y) (leq b (succ x) (succ y)))))
(assert (forall ((x Nat)) (leq false (succ x) zero)))
(assert (forall ((y Nat)) (leq true zero y)))
(declare-fun geq (Bool Nat Nat) Bool)
(assert (forall ((x Nat) (y Nat) (b Bool))
	(=>	(leq b y x) (geq b x y))))
(assert (forall ((x Nat) (y Nat) (z Nat) (x_16337 Bool) (x_16338 Bool) (x_16339 Bool))
	(=>	(and (= x_16337 false)
			(= x_16338 true)
			(= x_16339 true)
			(geq x_16337 x z)
			(geq x_16338 y z)
			(geq x_16339 x y))
		false)))
(check-sat)
```
(run with: `vampire --input_syntax smtlib2 --decode ott+11_3_aac=none:afr=on:afp=4000:afq=1.4:amm=off:anc=all:bs=unit_only:bsr=on:bce=on:fde=unused:irw=on:nm=64:newcnf=on:nwc=1:nicw=on:sac=on:sp=reverse_arity:uhcvi=on_31 file.smt2`).

Vampire halts with a saturation but it only contains a bunch of tautologies (instances of the excluded middle).

The thing I cannot understand is how can this saturation set represent a least Herbrand model of the original system. This is strange as I expected at least the original system to be included in the resulting saturated set, which is not true.

Also, if I substitute `x_16337` with `false` in the last clause (which I believe is a sound transformation), Vampire outputs nothing as a saturated set, which is even stranger to me.

P.S. I understand that my question is more related to theory than to Vampire as a tool, but I haven't found a better place for this question than GitHub Issues.

---
[1] Horbach, Matthias. "Saturation-based decision procedures for fixed domain and minimal model validity." (2010).

**Comment by Columpio** [comment]
What I have found is that there are only two options, which are necessary to reproduce this behavior:
- `--newcnf on`
- `-anc all`

Without the first one the system is no longer solvable. Without the second one an expected saturation set is returned.

**Comment by Columpio** [comment]
With `-bce on` and with `--newcnf off` the system is also solvable, but returns empty saturation set either.

**Comment by Columpio** [comment]
It looks like `newcnf` has a bug in negation propagation over boolean assignments:
```
[PP] ennf in: 7. ! [X0 : $bool,X1 : 'Nat()',X2 : $bool,X3 : $bool,X4 : 'Nat()',X5 : 'Nat()'] : ((($formula{X0} <=> $false) & ($formula{X2} <=> $true) & ($formula{X3} <=> $true) & geq(X0,X5,X4) & geq(X2,X1,X4) & geq(X3,X5,X1)) => $false) [flattening 6]
[PP] ennf out: 10. ! [X0 : $bool,X1 : 'Nat()',X2 : $bool,X3 : $bool,X4 : 'Nat()',X5 : 'Nat()'] : ($false | (($formula{X0} <~> $false) | ($formula{X2} <~> $true) | ($formula{X3} <~> $true) | ~geq(X0,X5,X4) | ~geq(X2,X1,X4) | ~geq(X3,X5,X1))) [ennf transformation 7]
```
All `<=>` equalities should flip, but they don't.
For comparison consider Vampire preprocessing with `--newcnf off`:
```
[PP] ennf in: 15. ! [X0 : $bool,X1 : 'Nat()',X2 : $bool,X3 : $bool,X4 : 'Nat()',X5 : 'Nat()'] : ~(($$true != X0) & ($$true = X2) & ($$true = X3) & geq(X0,X5,X4) & geq(X2,X1,X4) & geq(X3,X5,X1)) [flattening 14]
[PP] ennf out: 18. ! [X0 : $bool,X1 : 'Nat()',X2 : $bool,X3 : $bool,X4 : 'Nat()',X5 : 'Nat()'] : (($$true = X0) | ($$true != X2) | ($$true != X3) | ~geq(X0,X5,X4) | ~geq(X2,X1,X4) | ~geq(X3,X5,X1)) [ennf transformation 15]
```
Looks like #62 is related and this bug is already fixed. However, I obtain this behavior on the following Vampire version:
```
Vampire 4.5.1 (commit 57a6f78c on 2020-07-15 11:59:04 +0200)
```

**Comment by quickbeam123** [comment]
Hi Yurii, thank you for your interest in Vampire!

These are indeed most likely two bugs that we will attempt fixing soon.

Please note that the problem with saturated sets applies in general to strategies involving avatar (which your strategy implicitly uses); the avatar-specific `anc=all` makes the problem only more immediately visible.

**Comment by Columpio** [comment]
@quickbeam123, thank you for clarification.
Is there more stable release or safe option sequence for me as a workaround before you release a patch?

**Comment by quickbeam123** [comment]
Yes, for meaningful saturations use `av=off` and to avoid the problem with booleans don't use `newcnf=on`.

**Comment by selig** [comment]
Thanks for highlighting the issues. A general point is that we have not put much effort into considering what is 'useful' to have in a saturated set. Generally, Vampire tries hard to find a proof and the saturated set is meant to be a witness of it failing to do so but doesn't include information about (aggressive) preprocessing etc.  It's clear that we get this wrong in the presence of splitting at the moment.

To ensure that Martin's options work whilst using a portfolio mode  add "--forced_options av=off:newcnf=off" e.g.

./vampire --mode portfolio --schedule smtcomp --forced_options av=off:newcnf=off file.smt

**Comment by Columpio** [comment]
@selig, despite the fact that it should be investigated what is actually 'useful' inside the saturated set, I think there should be some theoretically-enforced properties which hold for output saturation set.
For example, my hypothesis is that if `S` is the original problem and `W` is it's saturation set, then the following must hold: `W ⊨ S`. So, for example, a set of tautologies (like in my problem with AVATAR) cannot be returned as a saturation set `W` in general case, as this property won't hold.

Are there any such properties? Could someone kindly refer me to some chapter of the "Handbook of automated reasoning" or some related paper?

**Comment by easychair** [comment]
I am not sure I have understood the concepts of "useful" or "meaningful" in
this context.

In any case, if we have a saturated set using AVATAR, the problem is
satisfiable: you take the model of the saturated set and additionally make
literals in the AVATAR model true to obtain the model of saturated set with
AVATAR conditions.

If this is not the case, there is a bug in the implementation.

Giles, do you mean that the bug is with preprocessing or that there is
additionally a bug in saturation with AVATAR on?

Andrei

**Comment by Columpio** [comment]
@quickbeam123 You have closed this issue by fixing AVATAR. However, there is also a bug in NewCNF, are there any fixes for that?

**Comment by easychair** [comment]
I somehow feel NewCNF should simply be reimplemented from scratch or
dropped. The number of serious unsoundness bugs since its introduction was
appalling.

Unfortunately, I've no time for it right now ...

A

**Comment by quickbeam123** [comment]
Yurii, yes, that was fixed with the other commits on 2 Jul. (To avoid confusion next time, please submit a separate issue for each potential bug you discover.)

(A, it would definitely make sense to have a closer look or reimplement from scratch. Apart from bugs, it's also not clear whether the current implementation fully explores the possibilities the top down view offers.)

**Comment by easychair** [comment]
> Yurii, yes, that was fixed with the other commits on 2 Jul. (To avoid confusion next time, please submit a separate issue for each potential bug you discover.)
>
> (A, it would definitely make sense to have a closer look or reimplement from scratch. Apart from bugs, it's also not clear whether the current implementation fully explores the possibilities the top down view offers.)

It was not just top-down. There were interesting techniques related to
if-then-else and boolean types.

A

**Comment by Columpio** [comment]
> Yurii, yes, that was fixed with the other commits on 2 Jul. (To avoid confusion next time, please submit a separate issue for each potential bug you discover.)

Thank you. It was not clear for me whether I encountered one bug or more. I will do my best to create more clear issue next time.
