### ISSUE TITLE
SMT-COMP schedule raises "No child process" exception

### ISSUE THREAD

**Issue by Columpio** [vprover/vampire#241]
If one runs Vampire on the following problem:
```smt2
(set-logic ALL)
(declare-sort Nat 0)
(declare-fun zero () Nat)
(declare-fun succ (Nat) Nat)
(declare-fun leq (Bool Nat Nat) Bool)
(assert (forall ((x Nat) (y Nat) (b Bool))
	(=>	(leq b x y) (leq b (succ x) (succ y)))))
(assert (forall ((x Nat)) (leq false (succ x) zero)))
(assert (forall ((y Nat)) (leq true zero y)))
(declare-fun geq (Bool Nat Nat) Bool)
(assert (forall ((x Nat) (y Nat) (b Bool))
	(=>	(leq b y x) (geq b x y))))
(assert (forall ((x Nat) (y Nat) (z Nat) (x_16337 Bool) (x_16338 Bool) (x_16339 Bool))
	(=>	(and (= x_16337 false)
			(= x_16338 true)
			(= x_16339 true)
			(geq x_16337 x z)
			(geq x_16338 y z)
			(geq x_16339 x y))
		false)))
(check-sat)
```
with the command:
```
$ vampire --input_syntax smtlib2 --mode portfolio --schedule smtcomp file.smt2
```
one obtains the following message:
```
% Exception at proof search level
System fail: Call to waitpid() function failed. error 10: No child processes
```
---
Vampire version:
```
Vampire 4.5.1 (commit 57a6f78c on 2020-07-15 11:59:04 +0200)
```

**Comment by selig** [comment]
Sounds like a potential race condition.

Did you build Vampire yourself or use a pre-build binary? 
Which OS are you running on?
Is this the only output you see?
Is it reproducible e.g. does it always happen/mostly happen?

**Comment by Columpio** [comment]
- I used latest release from github (4.5.1)
- Ubuntu 20.04.1:
  `$ uname -a`
  `Linux columpio-laptop 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- It's the only output. Maybe some debug/verbose flags/core dump will help?
- Mostly; on problems which usual Vampire does not solve in less than a second.

**Comment by ibnyusuf** [comment]
There is currently a bug in the Vampire scheduler such that when the logic `ALL` is selected, it adds zero strategies to the schedule and dies with the above (very bob-intuitive) error. We'll try and fix this soon. Until then, is there a more restrictive logic than `ALL` that could be used?

**Comment by selig** [comment]
I have made sure that the ALL logic does something sensible (on master branch) instead of crashing. However, it will still be best to use the most specific logic that applies if you know what this e.g. if it's in UF then use UF.
