### ISSUE TITLE
Reanimate Batch Mode

### ISSUE THREAD

**Issue by selig** [vprover/vampire#246]
A request from Adam Pease...

.... our internal batch (LTB) mode is a little broken and he was using it.

He doesn't need it to follow the CASC rules but wants to be able to load some joint axioms then pose a series of problems over those. Fixing it should not be that difficult, let's do it.

**Comment by MichaelRawson** [comment]
I don't understand how LTB in Vampire works. Is it explained anywhere?

Perhaps for this we only need a "simple" batch mode, rather than the competition version which seems to do something more elaborate. LTB in CASC is on hiatus, and it's not clear when or if it will return.

**Comment by apease** [comment]
I'd still love to have this capability, where we could ask multiple queries of Vampire without reloading

**Comment by MichaelRawson** [comment]
Is this closed @quickbeam123 ?

**Comment by apease** [comment]
It works for me on the latest release 7307.  This is a very helpful feature.
