### ISSUE TITLE
Official release 4.6

### ISSUE THREAD

**Issue by mdesharnais** [vprover/vampire#273]
Hi Vampire Team,
the performance of Vampire 4.6 at CASC-28 was impressive and I would like to integrate it into Isabelle/Sledgehammer. I am especially excited about the prospect of enabling higher-order and polymorphic reasoning!

Sadly the latest official release I can find is 4.5.1. Could you please officially release Vampire 4.6?

**Comment by quickbeam123** [comment]
Hi Martin,

I just added version 4.6. We hope it will make Isabelle/Sledgehammer even more user-friendly :)
