### ISSUE TITLE
TFF error message request

### ISSUE THREAD

**Issue by apease** [vprover/vampire#297]
When running

vampire --mode casc --proof tptp -t 1200 ~/.sigmakee/KBs/SUMO.tff

on the enclosed file (rename to .tff to replicate since GitHub doesn't allow that file extension) I get the following error message:

% Running in auto input_syntax mode. Trying TPTP
% Exception at proof search level
Parsing Error on line 268
The sort $int of term argument X9 is not an instance of sort $i

The relevant line is

tff(kb_SUMO_16,axiom,(! [V__ARG : $int,V__ARGS3 : $int,V__ARGS2 : $i,V__N : $i,V__VAL : $i] : (s__instance(V__ARGS2, s__Human) => (s__minValue(s__parents__m, V__ARG, V__N) & s__parents(V__ARGS2, V__ARGS3) & equal(V__VAL ,s__ListOrderFn(s__ListFn__2Fn__1In(V__ARGS3), V__ARG))) => greaterThan(V__VAL ,V__N)))).

Would it be possible to print the originally authored term instead of "X9", which I suspect is some label created by Vampire dynamically?

[SUMO.txt](https://github.com/vprover/vampire/files/7506324/SUMO.txt)

**Comment by quickbeam123** [comment]
Hi Adam, 
vampire does not have this information immediately available.
But would a message like the following be more helpful?
```
Parsing Error on line 268
Failed to create function application for s__ListFn__2Fn__1In of type ($i) > $i
The sort $int of the intended term argument X9 (at index 0) is not an instance of sort $i
```

**Comment by apease** [comment]
yes that would be great since it points out the problem within any larger axioms.  Many thanks for the quick response!

**Comment by apease** [comment]
At the risk of imposing on you, may I give another example with your fix and the following bad axiom

tff(kb_SUMO_1,axiom,(! [V__NUMBER1 : $real,V__NUMBER2 : $real] : ((equal(s__AbsoluteValueFn(V__NUMBER1) ,V__NUMBER2) => (equal(V__NUMBER1 ,V__NUMBER2) | equal(V__NUMBER2 ,$difference(0 ,V__NUMBER1)))) & ((equal(V__NUMBER1 ,V__NUMBER2) | equal(V__NUMBER2 ,$difference(0 ,V__NUMBER1))) => equal(s__AbsoluteValueFn(V__NUMBER1) ,V__NUMBER2))))).

% Running in auto input_syntax mode. Trying TPTP
% Exception at proof search level
Parsing Error on line 2557
Failed to create predicate application for equal of type ($i * $i) > $o
The sort $real of the intended term argument X1 (at index 1) is not an instance of sort $i

The error is at "index 1" but apparently that's not character 1 of the axiom.  If Vampire could indicate either the relation or the argument, that would allow the user to narrow down the error.  Now it just gives the signature.

**Comment by apease** [comment]
oops, please ignore my subsequent comment (now deleted).  Many thanks for your help!
