### ISSUE TITLE
The symbol $sum is not used with a single sort

### ISSUE THREAD

**Issue by stanmoon** [vprover/vampire#322]
I am trying to write simple proofs using sorts but cannot figure it out how to use equality for constants and integer functions.
Below a simple example:

`fof(simple_conj,conjecture,(
! [X: $int] : $sum(X,0) = X
)).`

Vampire output is as follows:

`The symbol $sum is not used with a single sort`

I'm using Vampire 4.5.1 (commit 57a6f78c on 2020-07-15 11:59:04 +0200)

Thanks!

**Comment by selig** [comment]
Try

`tff(simple_conj,conjecture,( ! [X: $int] : $sum(X,0) = X )).`

In fof mode Vampire will treat `$sum` as an uninterpreted function.

The error message does need improving!

**Comment by selig** [comment]
Correction. In fof mode, Vampire will treat `0` as an uninterpreted constant. `$sum` will be treated as interpreted.  The complaint is that `$sum` is being called on an uninterpreted input.

I have created a pull request (in progress) for a better error message. The improvement is currently meant to be

> The interpreted function symbol $sum is not used with a single sort.
> Argument 0 is $int and argument 1 is $i
> Check that you are using tff if you want numbers to be interpreted

Please say if you think this is still confusing.

**Comment by stanmoon** [comment]
Thank you, that explains it very well!
