### ISSUE TITLE
Wrong finite model with contour enumeration strategy

### ISSUE THREAD

**Issue by Columpio** [vprover/vampire#341]
I obtained a wrong finite model for the following problem:
```smt2
(set-logic UF)

(declare-sort Bol 0)
(declare-fun F () Bol)
(declare-fun T () Bol)
(assert (distinct T F))

(declare-sort Var 0)
(declare-fun x () Var)
(declare-fun y () Var)
(declare-fun z () Var)
(assert (distinct x y z))
(assert (forall ((c Var)) (or (= c x) (= c y) (= c z))))

(declare-sort Branch 0)
(declare-fun c1 () Branch)
(declare-fun c2 () Branch)
(declare-fun c3 () Branch)
(declare-fun c4 () Branch)
(assert (distinct c1 c2 c3 c4))
(assert (forall ((c Branch)) (or (= c c1) (= c c2) (= c c3) (= c c4))))

(declare-sort Code 0)
(declare-fun ret (Branch) Code)
(declare-fun switch (Var Code Code) Code)
(declare-fun nondet () Code)
(assert (forall ((b1 Branch) (b2 Branch)) (=> (distinct b1 b2) (distinct (ret b1) (ret b2)))))
(assert (forall ((b Branch)) (distinct (ret b) nondet)))
(assert (forall ((b Branch) (v Var) (fcase Code) (tcase Code)) (distinct (ret b) (switch v fcase tcase))))

(declare-fun m (Bol Bol Bol) Branch)
(assert (forall ((p1 Bol)) (= (m p1 F T) c1)))
(assert (forall ((p3 Bol)) (= (m F T p3) c2)))
(assert (forall ((p1 Bol) (p2 Bol))
	(=> (and (distinct p1 F) (distinct p2 T)) (= (m p1 p2 F) c3))))
(assert (forall ((p1 Bol) (p2 Bol))
	(=> (and (distinct p1 F) (distinct p2 F)) (= (m p1 p2 T) c4))))

(declare-fun eval (Code Bol Bol Bol Branch) Bool)
(assert (forall ((b Branch) (b1 Bol) (b2 Bol) (b3 Bol)) (eval nondet b1 b2 b3 b)))
(assert (forall ((c1 Code) (r1 Branch) (r2 Branch) (x1 Bol) (x2 Bol) (x3 Bol))
	(=> (and (eval c1 x1 x2 x3 r1) (eval c1 x1 x2 x3 r2)) (or (= r1 r2) (= c1 nondet)))))
(assert (forall ((br Branch) (b1 Bol) (b2 Bol) (b3 Bol)) (eval (ret br) b1 b2 b3 br)))
(assert (forall ((v Var) (fcase Code) (tcase Code) (b1 Bol) (b2 Bol) (b3 Bol) (b Branch))
	(=> (or (and (= v x) (= b1 F))
			(and (= v y) (= b2 F))
			(and (= v z) (= b3 F)))
		(=> (eval fcase b1 b2 b3 b) (eval (switch v fcase tcase) b1 b2 b3 b)))))
(assert (forall ((v Var) (fcase Code) (tcase Code) (b1 Bol) (b2 Bol) (b3 Bol) (b Branch))
	(=> (or (and (= v x) (= b1 T))
			(and (= v y) (= b2 T))
			(and (= v z) (= b3 T)))
		(=> (eval tcase b1 b2 b3 b) (eval (switch v fcase tcase) b1 b2 b3 b)))))

(declare-fun lt (Code Code) Bool)
(assert (forall ((v Var) (fcase Code) (tcase Code)) (lt fcase (switch v fcase tcase))))
(assert (forall ((v Var) (fcase Code) (tcase Code)) (lt tcase (switch v fcase tcase))))
(assert (forall ((v Var) (x Code) (y Code) (tcase Code)) (=> (lt x y) (lt x (switch v y tcase)))))
(assert (forall ((v Var) (x Code) (y Code) (fcase Code)) (=> (lt x y) (lt x (switch v fcase y)))))
(define-fun le ((c1 Code) (c2 Code)) Bool
	(or (= c1 c2) (lt c1 c2)))

(declare-fun query () Code)
(assert (forall ((b1 Bol) (b2 Bol) (b3 Bol) (b Branch)) (eval query b1 b2 b3 (m b1 b2 b3))))

(assert (forall ((q1 Code)) (=> (and (le q1 query) (lt q1 q1)) false)))
(assert (forall ((q1 Code)) (=> (le q1 query)
		(or (exists ((b Branch)) (= q1 (ret b)))
			(exists ((v Var) (fcase Code) (tcase Code)) (= q1 (switch v fcase tcase)))))))
```
The wrong part of the model is as below:
```
tff('declare_Var()',type,'Var()':$tType).
tff('declare_Var()1',type,x:'Var()').
tff('declare_Var()2',type,y:'Var()').
tff('declare_Var()3',type,z:'Var()').
tff('declare_Var()4',type,fmb_'Var()'_4:'Var()').
tff(finite_domain,axiom,
      ! [X:'Var()'] : (
         X = x | X = y | X = z | X = fmb_'Var()'_4
      ) ).

tff(distinct_domain,axiom,
         x != y & x != z & x != fmb_'Var()'_4 & y != z & y != fmb_'Var()'_4 & 
         z != fmb_'Var()'_4
).

tff('declare_Branch()',type,'Branch()':$tType).
tff('declare_Branch()1',type,c1:'Branch()').
tff('declare_Branch()2',type,c2:'Branch()').
tff('declare_Branch()3',type,c3:'Branch()').
tff('declare_Branch()4',type,c4:'Branch()').
tff('declare_Branch()5',type,fmb_'Branch()'_5:'Branch()').
tff(finite_domain,axiom,
      ! [X:'Branch()'] : (
         X = c1 | X = c2 | X = c3 | X = c4 | X = fmb_'Branch()'_5
      ) ).

tff(distinct_domain,axiom,
         c1 != c2 & c1 != c3 & c1 != c4 & c1 != fmb_'Branch()'_5 & c2 != c3 & 
         c2 != c4 & c2 != fmb_'Branch()'_5 & c3 != c4 & c3 != fmb_'Branch()'_5 & c4 != fmb_'Branch()'_5
).
```
As it can be observed from the input file, both `Var` and `Branch` sorts **should have fixed sizes 3 and 4** correspondingly, but the generated model violates this.

Run Vampire with: `vampire -sa fmb -av off -fmbes contour problem.smt2`
Vampire version commit: d5f6208aa5a21ec34eec2e5716d85f901cf4ee30
Importantly, I obtain a correct model if run Vampire with `-fmbes smt` and default `-fmbes sbeam`.

P.S. I tried to minimize the example, but failed: most formulas seem to be necessary to reproduce the bug. I'm really sorry with that.
P.P.S. Are there other ways to fix the finite model size besides the straightforward axiom introducing (like I did in the example above)?

**Comment by Columpio** [comment]
I even tried to substitute my `Var` declarations and assertions with a single statement `(declare-datatypes ((Var 0)) (((x) (y) (z))))` and I still obtain the model above, so this is essentially a bug of `contour` strategy.

**Comment by selig** [comment]
This is concerning indeed. I am glad that the error is contained to the `contour` strategy. This makes sense as well as this strategy uses a different method to compute and manipulate the sort sizes. We will investigate and hopefully there is a straightforward fix.

I can confirm I reproduce. Adding `--show_fmb_sort_info on` gives a little extra info

```
Sort Inference information:
5 inferred subsorts
Subsort 0 has 2 constants and 0 functions
Subsort 1 has 2 constants and 4 functions
Subsort 2 has 4 constants and 2 functions
Subsort 3 has 3 constants and 1 functions
Subsort 4 has 2 constants and 0 functions
5 distinct sorts
0 has 2 inferred subsorts as members [0,5]
1 has 2 inferred subsorts as members [3,6]
2 has 2 inferred subsorts as members [2,7]
3 has 2 inferred subsorts as members [1,8]
4 has 2 inferred subsorts as members [4,9]
Vampire to distinct sort mapping:
['Bol()','Var()','Branch()','Code()',$o]
Detected maximum model sizes of [2,max,max,max,2]
```

It is interesting that it doesn't detect the max size for Var or Branch. This will be the starting point for our investigation.

In the meantime, it seems that contour can be part of one of our portfolios. To avoid using contour when running in portfolio mode you can either add `--forced_options fmbes=sbeam` to make all fmb strategies use sbeam as an enumeration strategy  or `--forbidden-options fmbes=contour` to make all fmb strategies explicitly setting contour to fail without running.

**Comment by Columpio** [comment]
@selig As it tried, neither of `fmbes` strategies infers minimum and maximum sort cardinalities. Should it be another issue then?

**Comment by selig** [comment]
Hi,

@quickbeam123 took a look and noticed that the root cause here was the model printing code not reading the sort sizes from the right place. He wrote a fix that I've just reviewed and pushed to master. So the `sbeam` strategy was doing the right thing but then printing the wrong model.

I've realised that detecting maximum sort cardinalities is an orthogonal issue. It should never be a soundness thing and failing to detect max cardinalities only prevents us from return unsat when we should otherwise be able to. That being said, I'm working on a separate PR to re-add some removed functionality to detect max sort cardinalities, which may also improve performance.

**Comment by selig** [comment]
I have created the aforementioned pull request here: https://github.com/vprover/vampire/pull/346

Now for your example, I get

```
Vampire to distinct sort mapping:
['Bol()','Var()','Branch()','Code()',$o]
Detected minimum model sizes of [1,3,4,1,1]
Detected maximum model sizes of [2,3,4,max,2]
```

For the standard `sbeam` strategy we end up trying 5 fewer sort vectors (10 instead of 15) so, in general, we should hopefully see a performance improvement.
