### ISSUE TITLE
ghost statament color in Dafny on Visual Code

### ISSUE THREAD

**Issue by jiplucap** [vprover/vampire#374]
I filed this issue in stackoverflow:

Could I configure the color (grey, by default) of Ghost Statements in Dafny. I mean, the current gray color is too dark, it is difficult to see the text in the classroom screen. I think a lighter gray would be better.

I received the following answers:

-I think it makes more sense to file this as an issue on Github [github.com/dafny-lang/dafny/issues]
[James Wilcox](https://stackoverflow.com/users/438267/james-wilcox)

-I think [github.com/dafny-lang/ide-vscode/issues](https://github.com/dafny-lang/ide-vscode/issues) is right place to file this issue – [Divyanshu Ranjan](https://stackoverflow.com/users/14413069/divyanshu-ranjan)

-There are two options to fix this.
1.- Don't use markGhostStatements. By default dafny.markGhostStatements is set to be true. Change extension setting to false.
2.- Use markGhostStatements, but change background color. There is no configuration to set it. Probably file an issue at https://github.com/dafny-lang/ide-vscode to provide that configuration. You can locally build ide-vscode by setting this [option](https://github.com/dafny-lang/ide-vscode/blob/be6ee7b9dc626401c414d24c32924f6735cf4cf2/src/ui/ghostDiagnosticsView.ts#L13). 
See images below for change in background color by setting GhostDecoration.

![image](https://user-images.githubusercontent.com/23459019/170871584-9d637247-f44d-4d95-83b3-3db20662cf0a.png)
![image](https://user-images.githubusercontent.com/23459019/170871637-8b7e9d4a-ab6b-47f9-8214-35e8eeb0a451.png)

Thanks you.

**Comment by quickbeam123** [comment]
How is this a vampire issue?

**Comment by selig** [comment]
I agree with Divyanshu Ranjan when they say "I think [github.com/dafny-lang/ide-vscode/issues](https://github.com/dafny-lang/ide-vscode/issues) is right place to file this issue"

**Comment by jiplucap** [comment]
I am sorry, I tried to write it in https://github.com/dafny-lang/ide-vscode/issue .... I will do. 
Please, close this issue.
