### ISSUE TITLE
Suboptimal job distribution on multicore

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#379]
`PortfolioMode::performStrategy` + `getExtraSchedules` behaves in a suboptimal way, because as it calls `runSchedule` on a particular schedule it waits for it to fully finish, which, towards the end of its job, will only make part of the available cores busy. 

A solution will require turning the preparation and while-loop logic of `PortfolioMode::performStrategy` into a strategy generating stream to be passed to `runSchedule` once and for all.

**Comment by MichaelRawson** [comment]
I've been meaning to remove some of the scheduling complexity I sinfully added circa 2015 (!). I will do that and try to fix this at the same time.

**Comment by quickbeam123** [comment]
That's a great idea! (In the meantime @filipbartek will add some basic support for loading a schedule from a file.)

**Comment by filipbartek** [comment]
> In the meantime @filipbartek will add some basic support for loading a schedule from a file.

Done in #380.
