### ISSUE TITLE
Possible issue in substitution trees - check whether _nextVar really needs to keep growing forever

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#384]
(The problem being we would eventually run out `_nextVar`s - which actually happened before, in an actual run, when `SPEC_UPPER_BOUND` was "only" `10000000`, now it's about 50times larger.)

From Michael:

"We only "run out" of special variables because substitution trees do something a bit surprising with `_nextVar` to achieve freshness."

**Comment by MichaelRawson** [comment]
@ibnyusuf @joe-hauns - I *believe* this can now be closed and `SPEC_UPPER_BOUND` can be deleted. We no longer have "very special vars" so all special variables are just the right amount of special. What do you think?

**Comment by joe-hauns** [comment]
Yesss I think you're right. I think i just didn't spot that when i removed very special variables.

**Comment by MichaelRawson** [comment]
Thanks! I'll add it to the default-constructor PR.
