### ISSUE TITLE
Question about bitvector

### ISSUE THREAD

**Issue by TraceShadow** [vprover/vampire#430]
I have a smt2 file generated by z3 and uses bitvector. When I try to solve it with vampire, it returns me an error: indexed identifiers in general term position are not supported: (_ bv0 16), where bv0 is the name of the bitvector. I think the file I give to vampire is true because I can solve it with other solver. I wonder why such an error could have been made? Is there anything special about vampire? Thank you very much!

**Comment by quickbeam123** [comment]
Hi, unfortunately, Vampire currently does not support the SMT theory of bitvectors. The error message is a bit cryptic testimony to that.

**Comment by TraceShadow** [comment]
Sure, thank you!
