### ISSUE TITLE
Semantic Web: OWL vs. TPTP

### ISSUE THREAD

**Issue by blokhin** [vprover/vampire#47]
Dear community,

sorry for a very naive question from an amateur.
What is the recommended way to translate OWL2 into TPTP to be used with _vampire_, and which expressivity would be supported?

**Comment by blokhin** [comment]
ping

**Comment by simonr89** [comment]
Hello,

I am not very familiar with the topic, but [this paper](https://arxiv.org/pdf/1108.0155.pdf) should be relevant, if you haven't read it already.

It describes a translation to untyped first-order logic (FOF in TPTP parlance) but unfortunately the authors do not seem to provide a tool to perform that translation automatically.

**Comment by arademaker** [comment]
Hi @blokhin , I would recommend you the book https://dl.acm.org/citation.cfm?id=885746. Section 2.2.1.3 "Description languages as fragments of predicate logic" shows that ALC is a fragment of FOL and chapter 4 has more details. 

> So far, all Description Logics have been less expressive than first-order predicate logic (possibly with equality or counting quantifiers). In contrast, the expressive power of a Description Logic including the transitive closure of roles goes beyond first-order logic

**Comment by selig** [comment]
Closing as the question seems to be answered.

I'll add a final note that Geoff Sutcliffe of TPTP fame is a good answerer of such questions as he often needs to translate between input languages of various tools.
