### ISSUE TITLE
performance regression?

### ISSUE THREAD

**Issue by apease** [vprover/vampire#482]
I've tried the same enclosed TPTP file (a wumpus-world test problem with a few SUMO axioms) with older versions of vampire (4.3.0 and 4.6.1) and get an answer in well under a second.  The latest version takes 3.2 seconds.  Is this expected?
[temp-comb-new.tptp.txt](https://github.com/vprover/vampire/files/12422294/temp-comb-new.tptp.txt)
[out-vampnew.txt](https://github.com/vprover/vampire/files/12422311/out-vampnew.txt)
[out-vampold.txt](https://github.com/vprover/vampire/files/12422315/out-vampold.txt)

both run with 

vampire --proof tptp -t 10 temp-comb-new.tptp --mode casc

**Comment by MichaelRawson** [comment]
Hi Adam,

Thanks for the heads-up. It looks like the strategy schedule from the new Vampire chooses a strategy that doesn't work as well as the old Vampire. In principle this is not a performance regression, just that our strategies fit this particular instance less well than it did. That said, we still solve it!

Is this slowdown critical for you, or just something you noticed? There are a few ways around it with various tradeoffs we could explore.

**Comment by apease** [comment]
Many thanks for the immediate reply!  Since on our application we will have to ask a series of queries there is a usability difference between .2 and 3.2 second response times.  Is there a way to select the old strategy schedule?  Once we collect a set of queries in our domain is there an easy way to tune on them?  Maybe get Martin Suda's help with Snake?  Or would that require a much larger data set than a few dozen tests?

**Comment by MichaelRawson** [comment]
>Since on our application we will have to ask a series of queries

Related: I think we have #246 on this topic, but sadly I don't have the knowledge to fix it immediately. At some point doing this "directly" ought to be possible.

> Is there a way to select the old strategy schedule?

Yes - you are even persuading me that the old ones should stick around. I think users can also provide their own schedules if that's of interest to you. Anyway, you want `--mode portfolio --schedule casc_2019` - which does solve your problem quickly, like you say.

>Once we collect a set of queries in our domain is there an easy way to tune on them? Maybe get Martin Suda's help with Snake?

You can do it manually if you have a 'hunch' about what works, but this is hard. Or you can get indeed Martin or Andrei to help with Snake or Spider respectively - somehow we have two competing solutions to this admittedly-niche problem!

>Or would that require a much larger data set than a few dozen tests?

I think this would be fine, although I would be concerned about how well this would generalise if you wanted that. I believe the way both Snake and Spider work is by randomly sampling the space of strategies until a strategy is found that solves a problem, and the real magic happens only afterwards, so there is no requirement for some kind of 'curriculum' from easy problems to harder problems.

**Comment by apease** [comment]
Fantastic - using the old schedule gives us what we need for now.  Finding the best strategy is a hard problem, so just knowing we have options helps a great deal.  Thank you!

**Comment by MichaelRawson** [comment]
:-) Happy wumpus-hunting!
