### ISSUE TITLE
Revive `gcov`

### ISSUE THREAD

**Issue by inpefess** [vprover/vampire#516]
After trying to evaluate test coverage of the project, I realised that, historically, there was `gcov` support (flags in the old Makefile: https://github.com/vprover/vampire/blob/1dd0ea6a4eb21e5a58b67560763a6630dfdeb446/Makefile#L29 and even a script to generate reports from collected coverage data: https://github.com/vprover/vampire/blob/1dd0ea6a4eb21e5a58b67560763a6630dfdeb446/scripts/dogcov.sh).
In the CMake build, `gcov` seems to be gone, and reviving it poses some problems. Namely, it doesn't write coverage data because of a known `gcov` and `_exit` interplay problem (https://github.com/kr/ct/issues/12).
It seems that `_exit` (instead of more graceful `exit`) appeared in unit tests only to run them in Cygwin (https://github.com/vprover/vampire/commit/6279e2c8f19f50cdee281f5fd4985798769ecb06 with an explanation in https://github.com/vprover/vampire/wiki/Cygwin).

I propose adding `gcov` flags to CMake (in `Debug` mode) and updating the existing report-generation script.

I also propose to make coverage a Linux-only feature (by adding some `#ifdef CYGWIN` lines) since one can't have `exit` and `gcov` both working properly in Cygwin.

**Comment by MichaelRawson** [comment]
Relevant, from #517:

>[gcov] helped me identify functions not covered by other tests (Set.hpp already had a decent coverage) or specific cases missed by more general ones. I can create a PR for [this issue] based on my current pipeline and existing Giles' script.

---

>I propose adding gcov flags to CMake (in Debug mode) and updating the existing report-generation script.

If you are willing and it can be done mostly orthogonally to the rest of the build, I'd be very happy to merge it. I suspect others might use it too. I'd been intending to cleanup `scripts/`, it's mostly ancient. Having some green wood in there would be healthy.

>In the CMake build, gcov seems to be gone, and reviving it poses some problems.

Indeed - I'm not sure anyone used it for a long time. In the meantime the CMake build sprung into existence.

>It seems that _exit (instead of more graceful exit) appeared in unit tests only to run them in Cygwin

I'm not sure that anyone cares much about this case - maybe you do? If not, we could go back to `exit` and not bother with the Cygwin conditional-compile.

**Comment by inpefess** [comment]
> If you are willing and it can be done mostly orthogonally to the rest of the build, I'd be very happy to merge it.

I'll keep changes minimal and only for `Debug` section.

> I suspect others might use it too.

I hope it might be part of the CI pipeline one day!

> I'd been intending to cleanup `scripts/`, it's mostly ancient.

I guess at some point some scripts can become new custom targets described by CMake rather than standalone scripts.

> I'm not sure that anyone cares much about this case - maybe you do?

Not really.

> If not, we could go back to `exit` and not bother with the Cygwin conditional-compile.

Let's do it then!
