### ISSUE TITLE
Vampire on Cygwin: compilation and runtime errors

### ISSUE THREAD

**Issue by blanchette** [vprover/vampire#52]
I have tried to compile Vampire (master revisition 3893 from a few weeks ago) on Cygwin, so far without success. The compilation itself failed in a few places, due to undefined symbols in Unix headers (e.g. the "kill" function). It wasn't too hard to make things compile by changing two or three files, but when I tried to run "vampire_rel__.exe", without arguments, I immediately got this error:

    Floating point exception (core dumped)

For us Isabelle developers, it is crucial to make all the binary tools we include with Isabelle available on all three main platforms (Linux, Mac, and Windows). I would be grateful for any help.

**Comment by quickbeam123** [comment]
The Floating point exception should no longer occur with the latest version.

A principled way of sorting out the header issues will require more effort.

**Comment by quickbeam123** [comment]
Superseded by a new issue with a more fruitful discussion.
