### ISSUE TITLE
Unexpected "User error: This version cannot be used with this logic!"

### ISSUE THREAD

**Issue by ibnyusuf** [vprover/vampire#550]
When running current master on the attached file with options:

--mode portfolio --schedule smtcomp 

we receive the above user error. Exploration suggests that this is because the logic of the property object has not been set when it is queried in the schedule.
[out.txt](https://github.com/vprover/vampire/files/15210972/out.txt)

**Comment by MichaelRawson** [comment]
Should be fixed by [f9cebc5](https://github.com/vprover/vampire/commit/f9cebc54ff3e0015067cdc6dfa375fd504161e15).
