### ISSUE TITLE
UPDR incorrect (deletes too much) in the presence of specially parsed function definitions from SMT

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#561]
On: [00082minimized.txt](https://github.com/vprover/vampire/files/15393040/00082minimized.txt) we have master with
`--decode ott+2_1:1_updr=on:foolp=on_2` giving saturation, while with `--decode ott+2_1:1_updr=off:foolp=on_2` we find a proof.

@mezpusz is already after this one with https://github.com/vprover/vampire/compare/master...avoid-symbol-elimination-for-smtlib2-defined-symbols so, mostly, this issue tracks that we don't forget.

However, in addition to / instead of marking the relevant symbols as protected, it would be nice for the specially SMT-parsed function definitions to be turned back into normal formulas AT THE BEGINNING of the preprocessing pipeline under `-fnrw off` while their special treatment later on in the pipeline would only kick in for `-fnrw on`. Note that it might be necessary to mark both the actually parsed symbol as well as its "proxy" (named with the sFN_ /sPN_ prefix).

**Comment by mezpusz** [comment]
Thanks for creating the issue! I have a question though. So far I thought the `udpr=off` variant is the correct one, which means we are incomplete rather than unsound?

**Comment by quickbeam123** [comment]
You are right. I changed the issue's title.

**Comment by MichaelRawson** [comment]
Does #564 fix this issue and the duplicate?

**Comment by mezpusz** [comment]
The problem is fixed on the examples provided in both issues, so I would consider this solved.
