### ISSUE TITLE
bad test id errors

### ISSUE THREAD

**Issue by joe-hauns** [vprover/vampire#576]
Running vampire with the portfolio `snake_tptp_uns` all over smtlib and tptp gives quite some user errors of the shape `bad test id ins+<strategy-string>`. This is due to the removal of the `ins` saturation algorithm, which is still present in the schedule. 
What do you think we should do about this? Should we just remove all these strategies from the schedules?

**Comment by quickbeam123** [comment]
Sure, the `ins` strategies make no sense there anymore.

Please also note that `snake_tptp_uns` does not know anything about the SMTLIB logics etc, so the strategy dispatch could be quite broken there.
