### ISSUE TITLE
Finite model builder does not cope with updr removing functions / constants

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#59]
On the following problem

cnf(cl0, axiom, ~p1 |  p1 | Z != P).
cnf(cl1, axiom,  p2(Y,Y,f) | X = Y |  p2(P,Y,Z)).
cnf(cl2, axiom, ~p1 |  p2(R,X,Y) | Q != X).
cnf(cl3, axiom, ~p0 |  p2(P,Q,Z) | Z = P).
cnf(cl4, axiom, P != Q |  p2(Z,Q,X) |  p3(R,Q)).
cnf(cl5, axiom, ~p1 | ~p0 | ~p0).
cnf(cl6, axiom,  p1 |  p2(P,Z,X) | Q = R).
cnf(cl7, axiom,  p0 | ~p3(P,Q) | Y = P).
cnf(cl8, axiom, ~p1 |  p2(Z,P,X) | ~p1).
cnf(cl9, axiom, R = Z | P != Y |  p2(e,f,P)).

when run as in

./vampire -sa fmb

finite-model-builder's preprocessing removes all the function symbols while removing predicates (updr). Then the followup code tries to query the signature and finds it empty:

Condition in file ./Lib/DHMap.hpp, line 244 violated:
e
----- stack dump -----
Version : Vampire 4.3.0 (commit 7f955da3 on 2018-08-16 17:06:37 +0100)
Control points passed: 36292
last control point:
        -DHMap::findEntry (36292)
main
 vampireMode()
  doProving()
   ProvingHelper::runVampireSaturation
    ProvingHelper::runVampireSaturationImpl
     MainLoop::run
      FiniteModelBuilder::init
       SortInference::doInference

**Comment by inpefess** [comment]
Can't reproduce now:

```
vampire_rel_master_5343 -sa fmb             
Running in auto input_syntax mode. Trying TPTP
The problem is propositional so there are no sorts!
TRYING []
Finite Model Found!
% SZS status Satisfiable for 
% SZS output start FiniteModel for 
tff(declare_$i,type,$i:$tType).
tff(declare_$i1,type,fmb_$i_1:$i).
tff(finite_domain,axiom,
      ! [X:$i] : (
         X = fmb_$i_1
      ) ).

tff(declare_bool,type,$o:$tType).
tff(declare_bool1,type,fmb_bool_1:$o).
tff(finite_domain,axiom,
      ! [X:$o] : (
         X = fmb_bool_1
      ) ).

tff(declare_p1,type,p1: $o).tff(p1_definition,axiom,~p1).
tff(declare_p0,type,p0: $o).% p0 undefined
tff(declare_p2,type,p2: $i * $i * $i > $o ).
tff(predicate_p2,axiom,
%         p2(fmb_$i_1,fmb_$i_1,fmb_$i_1) undefined in model

).

tff(declare_p3,type,p3: $i * $i > $o ).
tff(predicate_p3,axiom,
%         p3(fmb_$i_1,fmb_$i_1) undefined in model

).

% SZS output end FiniteModel for 
% ------------------------------
% Version: Vampire 4.5.1 (commit d477b8746 on 2021-04-18 11:59:44 +0200)
% Termination reason: Satisfiable

% Memory used [KB]: 4861
% Time elapsed: 0.0000 s
% ------------------------------
% ------------------------------
```
