### ISSUE TITLE
FMB is returning partial/incorrect result

### ISSUE THREAD

**Issue by mmaroti** [vprover/vampire#621]
Just searching for all 2-element poset and encoding the problem as
```
tff(declared_dom, type, dom:$tType).
tff(declare_dom0, type, dom0: dom).
tff(declare_dom1, type, dom1: dom).
tff(dom_elements, axiom, ![X:dom]: (X=dom0 | X=dom1)).
tff(dom_distinct, axiom, $distinct(dom0, dom1)).
tff(declare_rel, type, rel: (dom * dom) > $o).
tff(axiom6, axiom, ![X:dom]: rel(X,X)).
tff(axiom7, axiom, ![X:dom, Y:dom, Z:dom]: ((rel(X,Y) & rel(Y,Z)) => rel(X,Z))).
```
Running this with `vampire -sa fmb` gives the result with :
```
tff(predicate_rel,axiom,
           rel(dom0,dom0)
%         rel(dom0,dom1) undefined in model
         & ~rel(dom1,dom0)
%         rel(dom1,dom1) undefined in model
).
```
This is not a model, as the undefined values cannot be arbitrarily set to any value.  How can I force the output relation to be fully defined?

**Comment by quickbeam123** [comment]
Thanks for the report, Miklos!

Restoring the values of eliminated symbols is an open issue that we plan to resolve within the next couple of months. (We will probably we able to point you to workarounds sooner, but current `master` has a small issue with model printing in general. Please stay tuned!)

**Comment by quickbeam123** [comment]
So, with the most recent commit, master should print your model correctly. 

Note that what's not implemented and will still take some time is model reporting in the presence of advanced preprocessing techniques (such as `blocked_clause_elimination`, `function_definition_elimination` or `unused_predicate_definition_removal`). If your input is (essentially) a plain cnf that triggers no such preprocessing, the models should already be fine.

**Comment by mmaroti** [comment]
Thanks, this has solved my issue!
