### ISSUE TITLE
Fiasco of your code.

### ISSUE THREAD

**Issue by yurivict** [vprover/vampire#65]
This instruction fails with ```Floating point exception```:
```
162│   inline Entry* firstEntryForCode(unsigned code) const
163│   {
164├───> return _entries + (code % _capacity);
165│   } // Map::firstEntryForCode
166│
```
```code=3223832701```
called from here:
```
126│     Entry* entry;
127├───> for (entry = firstEntryForCode(code); entry->occupied(); entry = nextEntry(entry)) {
128│       if (entry->code == code && Hash::equals(entry->key,key)) {
129│         found = entry->value;
130│         return true;
131│       }
132│     }
```
```
(gdb) bt
#0  0x00000000005fb2de in Lib::Map<Lib::Vector<unsigned int>*, Kernel::OperatorType*, Lib::PointerDereferencingHash>::firstEntryForCode (this=0x14b0308 <Kernel::OperatorType
::_operatorTypes>, code=3223832701) at ./Lib/Map.hpp:164
#1  0x00000000005f994f in Lib::Map<Lib::Vector<unsigned int>*, Kernel::OperatorType*, Lib::PointerDereferencingHash>::find (this=0x14b0308 <Kernel::OperatorType::_operatorTy
pes>, key=0x802667638, found=@0x7fffffffd500: 0x802667638) at ./Lib/Map.hpp:127
#2  0x00000000005f70e0 in Kernel::OperatorType::getTypeFromKey (key=0x802667638) at Kernel/Sorts.cpp:309
#3  0x00000000005e8606 in Kernel::OperatorType::getPredicateType (arity=2, sorts=0x0) at Kernel/Sorts.hpp:256
#4  0x00000000005dac28 in Kernel::Signature::Signature (this=0x802665d48) at Kernel/Signature.cpp:221
#5  0x00000000004344f3 in Lib::Environment::Environment (this=0x14b4b20 <Lib::env>) at Lib/Environment.cpp:67
#6  0x0000000000e4a777 in __cxx_global_var_init.12(void) () at Global.cpp:62
#7  0x0000000000e4a7ed in _GLOBAL__sub_I_Global.cpp () at /usr/include/c++/v1/__string:208
#8  0x0000000000e54e62 in __do_global_ctors_aux ()
#9  0x000000000040469e in _init ()
#10 0x00007fffffffdce0 in ?? ()
#11 0x00000008014636ba in objlist_call_init (list=<optimized out>, lockstate=<optimized out>) at /usr/src/libexec/rtld-elf/rtld.c:2647
#12 0x00000008014626ac in _rtld (sp=<optimized out>, exit_proc=0x7fffffffe7a0, objp=0x7fffffffe7a8) at /usr/src/libexec/rtld-elf/rtld.c:770
#13 0x00000008014606f9 in .rtld_start () at /usr/src/libexec/rtld-elf/amd64/rtld_start.S:39
#14 0x0000000000000000 in ?? ()
```

You access static variables from the static context which isn't allowed in C++.
This results in a ```static constructor fiasco```.

**Comment by easychair** [comment]
Sounds as scary as recent Ukranian naval ship maneuvers.

Let's try to understand this peacefully and using a fiasco-free vocabulary.

(1) Generally, I cannot see how pointer arithmetic can result in a floating
point exception, even after googling for a while. What do you mean by "this
instruction"? (we are not programming in assembly).
(2) Have you produced this behavior by taking procedures out of the static
variable initialization context used in Vampire or you have a concrete run
resulting in this behavior? If the latter, would you kindly share the input?

Best regards, Andrei

**Comment by yurivict** [comment]
> Sounds as scary as recent Ukranian naval ship maneuvers. Let's try to understand this peacefully and using a fiasco-free vocabulary.

```fiasco``` is a standard term describing this situation though. [1][2][3]

---------------

```_entries``` at this point was ```nullptr```, and ```_capacity``` was probably ```0```.
Where these fields are supposed to be filled?
When the crash happens due to null or zero, and this happens from the static context (before ```main```), ```static constructors fiasco``` is a suspect number one. Calling any complex code from the static constructors is a bad idea, in general.

---------------

Cheers,
Yuri


---References---
[1] https://isocpp.org/wiki/faq/ctors#static-init-order
[2] http://www.cs.technion.ac.il/users/yechiel/c++-faq/static-init-order.html
[3] http://www.dietmar-kuehl.de/mirror/c++-faq/ctors.html#faq-10.12

**Comment by easychair** [comment]
So it was division by 0. _entries does not matter. If you had a bit of
time you would quickly find out that _capacity is set by 32 in the
constructor (call of expand).

My guess is that at least 50% of C++ non-static functions would have a
run resulting in pointer or other problems if you don't call a
constructor first, so it is not useful when you contact developers
like this (and you should think before you publicly claim discovering
"fiascos" in other people's code like this).

I think any decent program analysis tool would derive that  _capacity
is always positive here.

A

**Comment by yurivict** [comment]
@easychair Sorry that your didn't get the joke in the title. -)

Now, I am only trying to create the FreeBSD port for your project, I don't necessarily have a lot of time to figure internal things out. When I build and run it, it crashes due to a division by zero. This information should be sufficient for you to fix this problem.

**Comment by yurivict** [comment]
The pointer itself doesn't look random:
```
(gdb) p (void*)this
$3 = (void *) 0x14b2318 <Kernel::OperatorType::_operatorTypes>
```
The object isn't initialized:
```
(gdb) p this
$6 = (const Lib::Map<Lib::Vector<unsigned int>*, Kernel::OperatorType*, Lib::PointerDereferencingHash> *) 0x14b2318 <Kernel::OperatorType::_operatorTypes>
(gdb) p *this
$4 = {_capacity = 0, _noOfEntries = 0, _entries = 0x0, _afterLast = 0x0, _maxEntries = 0}
```

The object in question is a static object in ```Kernel/Sorts.cpp```:
```
OperatorType::OperatorTypes OperatorType::_operatorTypes;
```

You use this object from the constructor of another statically constructed object ```Signature::Signature```.

The above use occurs in the static context:
```
(gdb) bt
#0  0x00000000005fd1ee in Lib::Map<Lib::Vector<unsigned int>*, Kernel::OperatorType*, Lib::PointerDereferencingHash>::firstEntryForCode (this=0x14b2318 <Kernel::OperatorType
::_operatorTypes>, code=3223832701) at ./Lib/Map.hpp:164
#1  0x00000000005fb85f in Lib::Map<Lib::Vector<unsigned int>*, Kernel::OperatorType*, Lib::PointerDereferencingHash>::find (this=0x14b2318 <Kernel::OperatorType::_operatorTy
pes>, key=0x802667638, found=@0x7fffffffd4f0: 0x802667638) at ./Lib/Map.hpp:127
#2  0x00000000005f8ff0 in Kernel::OperatorType::getTypeFromKey (key=0x802667638) at Kernel/Sorts.cpp:309
#3  0x00000000005ea516 in Kernel::OperatorType::getPredicateType (arity=2, sorts=0x0) at Kernel/Sorts.hpp:256
#4  0x00000000005dcb38 in Kernel::Signature::Signature (this=0x802665d48) at Kernel/Signature.cpp:221
#5  0x0000000000436403 in Lib::Environment::Environment (this=0x14b6b30 <Lib::env>) at Lib/Environment.cpp:67
#6  0x0000000000e4c727 in __cxx_global_var_init.12(void) () at Global.cpp:62
#7  0x0000000000e4c79d in _GLOBAL__sub_I_Global.cpp () at /usr/include/c++/v1/__string:208
#8  0x0000000000e56e12 in __do_global_ctors_aux ()
#9  0x00000000004046b6 in _init ()
#10 0x00007fffffffdcd0 in ?? ()
#11 0x00000008014656ba in objlist_call_init (list=<optimized out>, lockstate=<optimized out>) at /usr/src/libexec/rtld-elf/rtld.c:2647
#12 0x00000008014646ac in _rtld (sp=<optimized out>, exit_proc=0x7fffffffe790, objp=0x7fffffffe798) at /usr/src/libexec/rtld-elf/rtld.c:770
#13 0x00000008014626f9 in .rtld_start () at /usr/src/libexec/rtld-elf/amd64/rtld_start.S:39
#14 0x0000000000000000 in ?? ()
```

So my original off-the-cuff diagnostics was absolutely right. This is exactly what is known as ```C++ static constructor fiasco```. Like it was said before, C++ does not allow to use statically constructed C++ objects in the static context. Please fix this bug.

**Comment by easychair** [comment]
Some questions.

(1) What compiler are you using?
(2) What is the purpose of porting Vampire to BSD? I don't remember any
users asking for this.
(3) I do not like talking to anonymous people and likewise to people who
are absolutely right. Could you please

  (a) introduce yourself
  (b) explain what exactly you are after, since so far you are violating
Vampire's license.

Best regards,
Andrei

**Comment by yurivict** [comment]
> (1) What compiler are you using?

clang-60

> (2) What is the purpose of porting Vampire to BSD?

Creation of the port/package. This is usually done not on demand, but proactively, in the expectation that there would be users that will benefit from this. This is the first time I am being asked the question about the purpose. Usually software is developed with the expectation or hope that it will be used by a wide variety of people, even though this doesn't always work this way.

> (3) I do not like talking to anonymous people and likewise to people who are absolutely right. Could you please

> (a) introduce yourself

My name is Yuri. I am a FreeBSD committer. My interests span a wide range of topics in physics, chemistry, biochemistry and medicine. Technology-wise, I worked with software from the early 90s in functions up to being a project architect in science and algorithm intense software fields.

>  (b) explain what exactly you are after, since so far you are violating Vampire's license.

Creation of the port. Is this not allowed under the license?

Regards,
Yuri
