### ISSUE TITLE
ACFunEvaluator bug

### ISSUE THREAD

**Issue by daviddamestani** [vprover/vampire#69]
When running Vampire (debug version) on the following benchmark 

(declare-fun s () (Int))
(declare-fun t () (Int))
(define-fun F ((s (Int)) (t (Int))) Bool
true
)

(assert
 (not
  (and
  (=> (F s t) (exists ((x (Int))) (= (+ x s) t)))
  (=> (exists ((x (Int))) (= (+ x s) t)) (F s t))
  )
 )
)
(check-sat)
(exit)

We get an assertion Violation as such 

Condition in file ./Kernel/Signature.hpp, line 443 violated:
n < _funs.length()
Value of n is: 983295040
----- stack dump -----
Version : Vampire 4.3.0 (commit unknown)
Control points passed: 702421
last control point:
                   +Theory::isInterpretedFunction(unsigned) (702421)
main
 vampireMode()
  doProving()
   ProvingHelper::runVampireSaturation
    ProvingHelper::runVampireSaturationImpl
     MainLoop::run
      SaturationAlgorithm::runImpl
       SaturationAlgorithm::doOneAlgorithmStep
        SaturationAlgorithm::doUnprocessedLoop
         SaturationAlgorithm::newClausesToUnprocessed
          SaturationAlgorithm::addUnprocessedClause
           SaturationAlgorithm::doImmediateSimplification
            InterpretedEvaluation::perform
             InterpretedEvaluation::evaluateLiteral
              InterpretedLiteralEvaluator::evaluate
               InterpretedLiteralEvaluator::balancable
                Theory::isInterpretedFunction(TermList)
                 Theory::isInterpretedFunction(Term*)
                  Theory::isInterpretedFunction(unsigned)
----- end of stack dump -----

Note that this doesn't happen on Mac with default compilers.

So far this happens on Ubuntu 18.04.1 LTS with gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0 as a compiler.

**Comment by daviddamestani** [comment]
This comes from code in InterpretedLiteralEvaluator.cpp

_evals.push(new ACFunEvaluator<IntegerConstantType>(
		env.signature->getInterpretingSymbol(Theory::INT_PLUS),
		new IntEvaluator(),
		theory->representConstant(IntegerConstantType(0))));

**Comment by quickbeam123** [comment]
Should be fixed in 351a75da326729b73015bc910ed4d98
