### ISSUE TITLE
.smt2 triggers assertion violation under vampire-dbg 

### ISSUE THREAD

**Issue by emptylambda** [vprover/vampire#73]
Hello Vampire dev team, 

it seems like under `vampire-dbg` build, `.smt2` problems always trigger an assertion violation: 

```
Condition in file Kernel/InterpretedLiteralEvaluator.cpp, line 122 violated:
!error
----- stack dump -----
Version : Vampire 4.3.0 (commit e96a41d7 on 2019-06-01 22:02:36 +0100)
Control points passed: 153654
last control point:
                  -InterpretedLiteralEvaluator::tryEvaluateFunc (153654)
```

and at the source location:
```
ASS(!error); //we want to be informed of evaluation failures in debug mode
```

while `vampire-rel` can handle `.smt2` problems properly, I wonder if this assertion violation is intended outcome?

thanks in advance

**Comment by quicquid** [comment]
Hello - yes the assertion is too strong because it is also hit if a simplification fails due to an integer overflow. You can safely comment it out, I will remove it in the next days from the head.

**Comment by emptylambda** [comment]
https://github.com/vprover/vampire/commit/3e39925d715b969f8628b370d293f0e312fd0a8d
