### ISSUE TITLE
The readme mentions an ltb_mode script but it's not in /scripts

### ISSUE THREAD

**Issue by apease** [vprover/vampire#75]
Does the ltb_mode script still exist?  Or is there another way to load a .tptp or .tff file and ask multiple queries without reloading?

**Comment by quickbeam123** [comment]
There is "--mode casc_ltb" which triggers the functionality required to participate in the CASC competition's LTB division of the last years. (See e.g. http://www.tptp.org/CASC/J9/Design.html) I don't think the ltb_mode script is supported anymore.

**Comment by apease** [comment]
thanks @quickbeam123 !  Do you know of another way to run in a sort of "interactive" mode, asking queries or making assertions without reloading a background theory each time?

**Comment by quickbeam123** [comment]
I don't think there is one at the moment. But good to know there is demand for it!

**Comment by selig** [comment]
Some closing comments...

We explored the idea in a workshop paper: https://easychair.org/publications/paper/hCRF

Some of the ideas were partly implemented but it's all too old and broken to be useful now. It is something I'm interested to take up if there's a 'customer' for it.

If the context is wanting to do this as a batch then LTB does make sense and is still supported as described above.

**Comment by apease** [comment]
I'm still interested in a mode that allows the user to load a theory and ask multiple queries without reloading the entire theory.  This would be very useful for large theories such as SUMO which can have hundreds of thousands of statements.  For simple queries, the time to load is greater than the time to answer the query.  If I'm understanding some of the points in the workshop paper, it goes a step further of saving the state of proof, so that new queries or the addition of one assertion, doesn't cause the prover to start from scratch.  That's a different need, but also very useful.  Much of what I do with inference consists of testing answers for which SUMO may not have all the knowledge needed.  So there is interactive development of solutions to a query, using Vampire as a sort of proof assistant (like interactive HOL provers are used), and with my new editor https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7324012/
