### ISSUE TITLE
Erroneous code in DHMultiset

### ISSUE THREAD

**Issue by ibnyusuf** [vprover/vampire#81]
The following code is to be found in DHMultiset:

    inline
    Val next(unsigned& multiplicity)
    {
      CALL("DHMultiset::SetIterator::next/1");
      ASS_NEQ(_next, _afterLast);

      **multiplicity=_next->multiplicity;**
      return (_next++)->_val;
    }

The erroneous line is in bold. It should be _next->_info.multiplicity;

Why the code compiles without this fix is not clear to me.

**Comment by selig** [comment]
As this is inline in a header we won't try and compile it unless we use it. My assumption is that nobody was calling this line in the current version of Vampire. 

Fixed here: https://github.com/vprover/vampire/commit/5f951a3e7f59eb0a30916a7d4a797284fe1ae60c
