### ISSUE TITLE
mode casc_sat with propositional formulas

### ISSUE THREAD

**Issue by arademaker** [vprover/vampire#89]
the command below gives me a model that satisfies the problem. Can I ask for more than one model? Can I ask for all models of a propositional problem?

```bash
~/work/vampire/vampire --mode casc_sat  hamiltonian.p
```

**Comment by selig** [comment]
If you give Vampire a propositional problem it will just run a SAT solver (Minisat) and give the model returned by the SAT solver. If your interest is just in propositional problems then what you're after is an ALL-SAT solver, which can be simply implemented by adding blocking clauses to exclude the previous solution etc. You could do the same trick with Vampire (e.g. assert the negated model and ask again) but we don't support it directly. 

As a further point, if you know that you only want finite models then casc_sat mode is a bit too general as it may also give you a saturated set. To just look for finite models run with the option '--saturation_algorithm fmb' or if you want a broader set of strategies you could try adding '--forced_options sa=fmb' after '--mode casc_sat'.

**Comment by arademaker** [comment]
Just to register, the `forced_options sa=fmb` has a good performance impact:

```
$ time ~/work/vampire/vampire --mode casc_sat --forced_options sa=fmb -t 300 hamiltonian.p > /dev/null

real	0m0.032s
user	0m0.015s
sys	0m0.008s

$ time ~/work/vampire/vampire --mode casc_sat -t 300 hamiltonian.p > /dev/null

real	0m0.833s
user	0m0.809s
sys	0m0.027s
```
